spring:
  application:
    name: nvl-bot
  profiles:
    active: sqlite


server:
  port: 1337

shiro:
  ws:
    server:
      enable: true
      url: "/onebot/v11/ws"
  interceptor: xyz.harenk.nvl.bot.interceptor.MyInterceptor
